version: "3.9"
services:
  db:
    image: mongo:latest
    env_file:
      - ./.env
    ports:
      - 27017:27017
    volumes:
      - ./mongo/mongo.key:/mongo_ro.key:ro
      - ./mongo/check_rs.sh:/check_rs_ro.sh:ro
    entrypoint:
      - bash
      - -c
      - |
        cp /mongo_ro.key /mongo.key
        chmod 400 /mongo.key
        chown mongodb:mongodb /mongo.key
        cp /check_rs_ro.sh /check_rs.sh
        chmod +x /check_rs.sh
        exec docker-entrypoint.sh $$@
    healthcheck:
      test: ["CMD", "bash", "/check_rs.sh"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    command: ["mongod", "--keyFile", "/mongo.key", "--replSet", "rs0"]
